name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Import GPG key
        env:
          GPG_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          # Kill any existing gpg-agent
          pkill gpg-agent || true

          # Import the key
          echo "$GPG_KEY" > signing-key.asc
          gpg --batch --import signing-key.asc

          # Configure GPG
          mkdir -p ~/.gnupg
          echo "use-agent" > ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf

          # Start agent
          eval $(gpg-agent --daemon)
          echo "RELOADAGENT" | gpg-connect-agent

      - name: Make gradlew executable
        working-directory: ./android
        run: chmod +x gradlew

      - name: Build
        working-directory: ./android
        run: ./gradlew clean build

      - name: Publish to Maven Central
        if: github.ref == 'refs/heads/main'
        working-directory: ./android
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          GPG_TTY: $(tty)
        run: |
          export GPG_TTY=$(tty)
          ./gradlew publish --info
